### ISSUE TITLE
count funcとかfile funcとかはclassを作ってその中にメソッドを書く、グローバル変数を極力なくす

### ISSUE THREAD

**Issue by kboy-silvergym** [miyaji555/sepak_judge#2]
## ①ちゃんとクラス分けする

例えば [count_funcs.dart](https://github.com/miyaji555/sepak_judge/blob/master/lib/count_funcs.dart) は、ファイル分されてるだけでSetServerとかのメソッドがクラス配下にないので、いわゆるグローバル変数っていうどこからでもアクセスできる状態になっている。

なので、使うところからだけ呼ぶというルールにするために、例えば、 `count_funcs.dart` だったら

```dart
class CountUtils {
  setServer() {
  
  }

  checkIfDeuce() {
  
  }
}
```

みたいに書いて、呼ぶときは、

```dart

final countUtils = CountUtils()
countUtils.setServer()
```

みたいにしたい。これは一旦細かい話で頭置いといてもらって、次の節で説明するのがやってほしいこと。

## ②グローバル変数を極力なくす

上のやつを書いてて気づいたんだけど、

例えば `ATeamWin ` が　https://github.com/miyaji555/sepak_judge/blob/c70d8c5760ac02feda6acf81dda12d5bba7ed941/lib/point_counting.dart　 
 とかにグローバルで書かれていて、どこからでもいじれるようにしてて、それをcount_funcs.dartとかで操作している。

これだと、どこに何が書いてあるか分からないし、上の①をやったら、アクセスできないエラーとか増えると思う。

なので、MatchとかGameとかいう試合の１単位を示すclassをまず作ろう。

```dart
class Match {


}
```

この中に https://github.com/miyaji555/sepak_judge/blob/c70d8c5760ac02feda6acf81dda12d5bba7ed941/lib/point_counting.dart 　に書いてある変数一覧があるイメージ

```dart
class Match {

bool server = true; //TeamAがサーブ権を得た場合true,TeamBがサーブ権を得た場合false
List ServerList = new List.filled(50, false);
int SetNumber = 1;
var ATeamName = FileContentsList[1];
var BTeamName = FileContentsList[2];
var AScore = [0, 0, 0]; //なぜか配列からTextに出力できない
var BScore = [0, 0, 0];
var SetCount = [
  0,
  0,
  0
]; //そのセットが行われていなければ０、Ateamがそのセットをとっていたら１、BTeamがそのセットをとっていたら-1
var APoint = 0;
var BPoint = 0;
int count = 0;
bool side = true;
bool deuce = false;
bool ATeamWin = false;
bool BTeamWin = false;
int Winner = 0; //Ateamが勝てば１、BTeamが勝てば−１
bool GameSet = false;
List ACounter = new List.filled(50, false);
List BCounter = new List.filled(50, false);

}
```

取り急ぎは、このマッチの中に、count_funcs.dartとかにあるメソッドを移動したら良さそう。

**Comment by miyasic** [comment]
グローバル変数を極力減らすために上記にあるようにクラスを作成しました。
その結果、画面遷移時の値の受け渡しが分からないことに気がつきました。
以前のflutter大学では値の受け渡しの説明をされてましたが、providerパターンではなく、わかりませんでした。providerパターンでの値の受け渡しはどうやりますか？

**Comment by kboy-silvergym** [comment]
基本providerでもやり方一緒ですよ！
画面に渡したあとそれをモデルにも渡す感じ

**Comment by miyasic** [comment]
例えばPointCountingPageクラスで

`PointCounting(this.name); final String name`
としてnameに値を受け取って
PointCountingModelクラスでも
`PointCounting(this.name);final String name`
とやって値を受け取るイメージですか？

また、この値をMatchクラスのインスタンス？（言葉がわかりません）であるPointCountingModelMatch.ATeamnameのように受け取ることはできますか？
`PointCountingModel(this.PointCountingModelMatch.ATeamName);
final PointCountingModelMatch = match();`
このような書き方ではうまくいきませんでした。

**Comment by kboy-silvergym** [comment]
あえて、少ない言葉で説明しますが、


どこかで

```dart
final match = PointCountingModelMatch();
```

みたいの作って、それを

```dart
PointCountingPage(this.match);
final PointCountingModelMatch match;
```

って感じで定義すれば, matchごと渡せるので、matchのインスタンスの中に入っているATeamNameの値も丸ごと渡せるイメージです。matchのインスタンスの中に含まれているので。

**Comment by miyasic** [comment]
ありがとうございました。恐らく出来ました。
